
###
GET http://localhost:4000/emp-api/employees
###
POST http://localhost:4000/emp-api/employee
Content-Type: application/json

{
  "name": "lokesh sadhu",
  "email": "lokesh@example.com",
  "mobile": 6281887958,
  "designation": "Software Engineer",
  "companyname": "TCS"
}

###
POST http://localhost:4000/emp-api/employee
Content-Type: application/json

{
  "name": "Priya Reddy",
  "email": "priya@example.com",
  "mobile": 9123456780,
  "designation": "Frontend Developer",
  "companyname": "Infosys"
}

###
POST http://localhost:4000/emp-api/employee
Content-Type: application/json

{
  "name": "Sneha Patel",
  "email": "sneha@example.com",
  "mobile": 9090909090,
  "designation": "QA Engineer",
  "companyname": "Capgemini"
}

###
POST http://localhost:4000/emp-api/employee
Content-Type: application/json

{
  "name": "Kiran Das",
  "email": "kiran@example.com",
  "mobile": 8888888888,
  "designation": "DevOps Engineer",
  "companyname": "Accenture"
}

###
PUT http://localhost:4000/emp-api/employee/69ca1bc3c62fad2cd22d4766
Content-Type: application/json

{
  "designation": "Senior Software Engineer"
}

###
DELETE http://localhost:4000/emp-api/employee/69ca1bc3c62fad2cd22d4766