
###
GET http://localhost:4000/products
###
GET http://localhost:4000/products/brand/HP 
###
GET http://localhost:4000/products/6
###
POST http://localhost:4000/products
Content-Type: application/json

{
    "productId":1,
    "name":"laptop",
    "brand":"HP",
    "price":40000
}
###
POST http://localhost:4000/products
Content-Type: application/json

{
    "productId":2,
    "name":"laptop",
    "brand":"MAC",
    "price":65000
}
###
POST http://localhost:4000/products
Content-Type: application/json

{
    "productId":3,
    "name":"Mobile",
    "brand":"SAMSUNG",
    "price":40000
}
###
POST http://localhost:4000/products
Content-Type: application/json

{
    "productId":4,
    "name":"HeadPhones",
    "brand":"BOAT",
    "price":4000
}
###
POST http://localhost:4000/products
Content-Type: application/json

{
    "productId":5,
    "name":"laptop",
    "brand":"DELL",
    "price":80000
}
###
POST http://localhost:4000/products
Content-Type: application/json

{
    "productId":6,
    "name":"mobile",
    "brand":"REDMI",
    "price":20000
}
###
POST http://localhost:4000/products
Content-Type: application/json

{
    "productId":7,
    "name":"mobile",
    "brand":"APPLE",
    "price":60000
}
###
POST http://localhost:4000/products
Content-Type: application/json

{
    "productId":8,
    "name":"laptop",
    "brand":"ASUS",
    "price":45000
}
### Can update the resources
PUT http://localhost:4000/products
Content-Type: application/json 

{
    "productId":8,
    "name":"laptop",
    "brand":"MAC",
    "price":100000
    
}
### used for deleting products using id 
DELETE http://localhost:4000/products/1